### ISSUE TITLE
后端：模型处理

### ISSUE THREAD

**Issue by Janet731** [Ethkuil/Machine-Learning-Model-Serving#4]
任务内容：
读取pmml和onnx格式的模型:
- [ ] 「查看模型信息」：类似 DaaS 平台的信息，包括输入（字段名、类型、取值[如有]、维数[如有]）和目标变量（已完成）
<img width="907" alt="Screen Shot 2022-08-18 at 3 17 37 PM" src="https://user-images.githubusercontent.com/80447968/185333883-e01ffd86-f110-479c-aca4-146dea0d4f17.png">

- [ ] 「添加模型」（已完成）
<img width="912" alt="Screen Shot 2022-08-18 at 1 07 06 PM" src="https://user-images.githubusercontent.com/80447968/185298629-3e629c89-f4c6-4183-a88b-67d64fd09a7e.png">

- [ ] 「删除模型」（已完成）
<img width="907" alt="Screen Shot 2022-08-18 at 1 07 14 PM" src="https://user-images.githubusercontent.com/80447968/185298658-079c41a4-7395-4265-a669-7e3d26e5dbaf.png">

- [ ] 「测试模型」:能够测试模型，通过表单输入数据（表单项可能是文本也可能是文件，类似 postman）或者
使用 JSON 命令直接输入 JSON 格式的数据，提交后预测结果会显示在界面中
（onnx目前跑logreg_iris.onnx没有问题，出现其他数据类型可能有bug，pmml目前跑xgb-iris.pmml没有问题，但出现其他数据类型可能有bug）
<img width="907" alt="Screen Shot 2022-08-18 at 3 19 46 PM" src="https://user-images.githubusercontent.com/80447968/185334127-53ce8276-de77-4117-b742-07f8092142a6.png">
<img width="931" alt="Screen Shot 2022-08-18 at 10 04 20 PM" src="https://user-images.githubusercontent.com/80447968/185414699-a7f97945-05e3-45a9-9329-1f954b18b810.png">

**Comment by Ethkuil** [comment]
这里的「后端：模型处理」只包括「查询模型信息」，还是说也包括「添加模型」、「删除模型」、「测试模型」什么的？

**Comment by Ethkuil** [comment]
模型信息部分，必要的只有id、name、type、输入变量、目标变量. 其他信息是抄DaaS的，大作业文档无强制要求，不方便实现的话可以删掉。

**Comment by chachaw** [comment]
那个模型读取能写一些帮助吗，比如具体实现和如何使用。
我到时候改api。

**Comment by Janet731** [comment]
啊我改一下再提交吧我昨天交的这个太混乱了而且还有很多功能还没实现😭

> 那个模型读取能写一些帮助吗，比如具体实现和如何使用。 我到时候改api。
